services:
  api-gateway:
    container_name: api-gateway
    image: api-gateway:latest
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - resource-server
    networks:
      - microservices-network

  resource-server:
    container_name: resource-server
    image: resource-server:latest
    build:
      context: ./resource-server
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge