server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: resource-server # unique identifier for the route
          uri: http://resource-server:8082 # destination that this route forwards requests to
          predicates:
            - Path=/api/resource/** # requests matching this path will be routed to this resource
          filters:
            - TokenRelay=
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: my-keycloak
            client-id: keycloak-auth
            client-secret: d6ShCxEUgwEbQVSYhnfXPDQVtdxQLNJH
            authorization-grant-type: authorization_code
            redirect-uri: http://api-gateway:8081/login/oauth2/code/{registrationId}
            scope: openid
        provider:
          my-keycloak:
            issuer-uri: http://keycloak-auth:7080/realms/my_realm