server:
  port: ${API_GATEWAY_PORT}

spring:
  application:
    name: ${API_GATEWAY_NAME}
  cloud:
    gateway:
      routes:
        - id: resource-server # unique identifier for the route
          uri: ${API_GATEWAY_RESOURCE_URI} # destination that this route forwards requests to
          predicates:
            - Path=/api/resource/** # requests matching this path will be routed to this resource
          filters:
            - TokenRelay=
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: ${API_GATEWAY_OAUTH2_CLIENT_PROVIDER}
            client-id: ${API_GATEWAY_OAUTH2_CLIENT_ID}
            client-secret: ${API_GATEWAY_OAUTH2_CLIENT_SECRET}
            authorization-grant-type: ${API_GATEWAY_OAUTH2_GRANT_TYPE}
            redirect-uri: ${API_GATEWAY_OAUTH2_REDIRECT_URI}
            scope: ${API_GATEWAY_OAUTH2_SCOPE}
        provider:
          my-keycloak:
            issuer-uri: ${API_GATEWAY_OAUTH2_ISSUER_URI}