server:
  port: ${RESOURCE_SERVER_PORT}

spring:
  application:
    name: ${RESOURCE_SERVER_NAME}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${RESOURCE_SERVER_OAUTH2_ISSUER_URI}